import type { Metadata } from "next";
import { Geist, Geist_Mono, Mitr } from "next/font/google";
import "./globals.css";
import { AlertPopUpUI } from "@/components/pop-up/AlertPopUp";
import { ConfirmPopUpUI } from "@/components/pop-up/ConfirmPopUp";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const mitr = Mitr({
  variable: "--font-mitr",
  subsets: ["latin", "thai"],
  weight: ["200", "300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${mitr.variable} font-sans antialiased`}
      >
        <AlertPopUpUI>
          <ConfirmPopUpUI>{children}</ConfirmPopUpUI>
        </AlertPopUpUI>
      </body>
    </html>
  );
}
