import { Request } from "@/types/request.type";
export const USE_MOCK_DATA = true;
export const MOCK_REQUESTS: Request[] = [
  {
    RequestID: "req-001",
    CampusID: 1,
    RequestOwner: "user-001",
    CreatedAt: "2026-01-15T10:30:00.000Z",
    AwardID: "award-001",
    status: "PENDING_HEAD",
    Owner: {
      user_id: "user-001",
      email: "somchai.s@example.com",
      fname: "สมชาย",
      lname: "ใจดี",
      role: "STUDENT",
      prefix: "นาย",
      username: "66130001",
    },
    Award: {
      award_id: "award-001",
      award_name: "รางวัลนักศึกษาดีเด่น",
      award_type: "academic",
      description: "รางวัลสำหรับนักศึกษาที่มีผลการเรียนดีเด่น",
      is_active: true,
    },
  },
  {
    RequestID: "req-002",
    CampusID: 1,
    RequestOwner: "user-002",
    CreatedAt: "2026-01-20T14:15:00.000Z",
    AwardID: "award-002",
    status: "PENDING_VICEDEAN",
    Owner: {
      user_id: "user-002",
      email: "malee.k@example.com",
      fname: "มาลี",
      lname: "สุขสันต์",
      role: "STUDENT",
      prefix: "นาง",
      username: "66130002",
    },
    Award: {
      award_id: "award-002",
      award_name: "รางวัลนักกีฬาดีเด่น",
      award_type: "sports",
      description: "รางวัลสำหรับนักกีฬาที่มีผลงานโดดเด่น",
      is_active: true,
    },
  },
  {
    RequestID: "req-003",
    CampusID: 1,
    RequestOwner: "user-003",
    CreatedAt: "2026-02-01T09:00:00.000Z",
    AwardID: "award-003",
    status: "REJECTED_BY_HEAD",
    Owner: {
      user_id: "user-003",
      email: "prasert.w@example.com",
      fname: "ประเสริฐ",
      lname: "วงศ์ดี",
      role: "STUDENT",
      prefix: "นาย",
      username: "66130003",
    },
    Award: {
      award_id: "award-003",
      award_name: "รางวัลบริการสังคม",
      award_type: "service",
      description: "รางวัลสำหรับนักศึกษาที่ทำคุณประโยชน์ต่อสังคม",
      is_active: true,
    },
  },
  {
    RequestID: "req-004",
    CampusID: 1,
    RequestOwner: "user-004",
    CreatedAt: "2026-02-05T16:45:00.000Z",
    AwardID: "award-004",
    status: "PENDING_DEAN",
    Owner: {
      user_id: "user-004",
      email: "nisa.p@example.com",
      fname: "นิษา",
      lname: "พรหมพิทักษ์",
      role: "STUDENT",
      prefix: "นางสาว",
      username: "66130004",
    },
    Award: {
      award_id: "award-004",
      award_name: "รางวัลนักวิจัยรุ่นใหม่",
      award_type: "research",
      description: "รางวัลสำหรับนักศึกษาที่มีผลงานวิจัยดีเด่น",
      is_active: true,
    },
  },
  {
    RequestID: "req-005",
    CampusID: 1,
    RequestOwner: "user-005",
    CreatedAt: "2026-02-08T11:20:00.000Z",
    AwardID: "award-005",
    status: "NEEDS_DOCS",
    Owner: {
      user_id: "user-005",
      email: "warin.t@example.com",
      fname: "วรินทร",
      lname: "ทองคำ",
      role: "STUDENT",
      prefix: "นาย",
      username: "66130005",
    },
    Award: {
      award_id: "award-005",
      award_name: "รางวัลผู้นำนักศึกษา",
      award_type: "leadership",
      description: "รางวัลสำหรับนักศึกษาที่เป็นผู้นำและมีคุณธรรม",
      is_active: true,
    },
  },
  {
    RequestID: "req-006",
    CampusID: 1,
    RequestOwner: "user-006",
    CreatedAt: "2026-02-10T13:30:00.000Z",
    AwardID: "award-001",
    status: "PENDING_SD",
    Owner: {
      user_id: "user-006",
      email: "kanya.m@example.com",
      fname: "กัญญา",
      lname: "มีชัย",
      role: "STUDENT",
      prefix: "นางสาว",
      username: "66130006",
    },
    Award: {
      award_id: "award-001",
      award_name: "รางวัลนักศึกษาดีเด่น",
      award_type: "academic",
      description: "รางวัลสำหรับนักศึกษาที่มีผลการเรียนดีเด่น",
      is_active: true,
    },
  },
  {
    RequestID: "req-007",
    CampusID: 1,
    RequestOwner: "user-007",
    CreatedAt: "2026-02-09T10:15:00.000Z",
    AwardID: "award-002",
    status: "PENDING_SD",
    Owner: {
      user_id: "user-007",
      email: "supachai.l@example.com",
      fname: "ศุภชัย",
      lname: "ลิขิตพงศ์",
      role: "STUDENT",
      prefix: "นาย",
      username: "66130007",
    },
    Award: {
      award_id: "award-002",
      award_name: "รางวัลนักกีฬาดีเด่น",
      award_type: "sports",
      description: "รางวัลสำหรับนักกีฬาที่มีผลงานโดดเด่น",
      is_active: true,
    },
  },
  {
    RequestID: "req-008",
    CampusID: 1,
    RequestOwner: "user-008",
    CreatedAt: "2026-02-07T15:45:00.000Z",
    AwardID: "award-004",
    status: "PENDING_COMMITTEE",
    Owner: {
      user_id: "user-008",
      email: "orawan.p@example.com",
      fname: "อรวัน",
      lname: "ปรีชา",
      role: "STUDENT",
      prefix: "นางสาว",
      username: "66130008",
    },
    Award: {
      award_id: "award-004",
      award_name: "รางวัลนักวิจัยรุ่นใหม่",
      award_type: "research",
      description: "รางวัลสำหรับนักศึกษาที่มีผลงานวิจัยดีเด่น",
      is_active: true,
    },
  },
];
